title: Foundation for Public Code
permalinks: pretty

remote_theme: publiccodenet/jekyll-theme
description: Enabling public-purpose software and policy that is open and collaborative. We help open source projects for public organizations to become successful, build sustainable communities around them and create a thriving public open source ecosystem. We do this through codebase stewardship of both software and civic code.

titles_from_headings:
  strip_title: true

show_breadcrumbs: true
toc: true

# Include well known file needed for matrix / riot.im service discovery
include:
  - .well-known
  - OSPO.md

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "who-we-are/team"
    values:
      layout: "bio"
      toc: false
